// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmmtpddwhkpryeytedpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttbXRwZGR3aGtwcnlleXRlZHByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDQyNDgsImV4cCI6MjA2NTMyMDI0OH0.4S7G6jWMsmSqgrwph4w3qa-_CxrL00VllBVGWHOMjYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);